version: "3.8"

services:
  node-app:
    build:
      context: ./node-app
    container_name: fileserver
    # We do NOT map 8080 to the host, because we want all traffic through NGINX
    volumes:
      # Mount a host folder for persisted uploads
      - /home/takacsstephan/fileServerUploads
    networks:
      - mynet

  nginx:
    build:
      context: ./nginx
    container_name: my-nginx
    # Expose NGINX to the host on port 80 (and maybe 443 later)
    ports:
      - "80:80"
    depends_on:
      - node-app
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
